/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedEditor: typeof import('./components/AdvancedEditor/AdvancedEditor.vue')['default']
    AdvancedForm: typeof import('./components/AdvancedForm/AdvancedForm.vue')['default']
    AgentFormFrame: typeof import('./components/DefineClientInstance/AgentFormFrame/AgentFormFrame.vue')['default']
    AppLayout: typeof import('./components/Interface/AppLayout/AppLayout.vue')['default']
    AppLayoutDrawer: typeof import('./components/Interface/AppLayout/AppLayoutDrawer.vue')['default']
    AppLayoutToolbar: typeof import('./components/Interface/AppLayout/AppLayoutToolbar.vue')['default']
    AppToast: typeof import('./components/Interface/AppLayout/AppToast.vue')['default']
    DefaultLayout: typeof import('./components/Interface/Layouts/DefaultLayout/DefaultLayout.vue')['default']
    DefineClientInstance: typeof import('./components/DefineClientInstance/DefineClientInstance.vue')['default']
    EmptyLayout: typeof import('./components/Interface/Layouts/EmptyLayout/EmptyLayout.vue')['default']
    EntitiesForm: typeof import('./components/EntitiesForm/EntitiesForm.vue')['default']
    JsonEditor: typeof import('./components/JsonEditorCard/JsonEditor.vue')['default']
    JsonEditorCard: typeof import('./components/JsonEditorCard/JsonEditorCard.vue')['default']
    RequestEditor: typeof import('./components/RequestEditor/RequestEditor.vue')['default']
    ResponseDrawer: typeof import('./components/ResponseDrawer/ResponseDrawer.vue')['default']
    ResponseViewer: typeof import('./components/ResponseViewer/ResponseViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
